export interface SubModuleDefinition {
  id: string
  name: string // e.g. "THE SILENT REALITY"
  eyebrow?: string // e.g. "THE SILENT REALITY"
  title: string // e.g. "The problem nobody talks about."
  description?: string
  defaultMediaUrl: string
  defaultSourceType: 'url' | 'localhost'
  defaultTitle: string
  mediaType?: 'video' | 'photo'
  aspectRatio?: 'video' | 'portrait' | 'square' | 'wide'
  placement?: string
}

export interface SectionDefinition {
  id: string
  name: string
  subRoute?: string
  description: string
  defaultMediaUrl: string
  defaultSourceType: 'url' | 'localhost'
  defaultTitle: string
  subModules?: SubModuleDefinition[]
}

export interface PageMediaItem {
  id: string
  pageName: string
  pageSlug: string
  pageId: string
  sectionId?: string
  sectionName: string
  subModuleId?: string
  subModuleName?: string // e.g. "THE SILENT REALITY", "ORIGIN STORY"
  title: string
  description?: string
  mediaType: 'video' | 'photo'
  sourceType: 'url' | 'localhost'
  mediaUrl: string
  thumbnailUrl?: string
  isActive: boolean
  createdAt: string
  order?: number
}

export interface WebsitePageConfig {
  id: string
  name: string
  slug: string
  livePath: string
  description: string
  sections: SectionDefinition[]
}

/**
 * Strict Website Navigation Page Items & Section Directories
 * Matching the exact website header menu and mega-menus from screenshots:
 * Home Page | Our World | Circles | Membership | Leadership | Unity | Community Life | About
 */
export const WEBSITE_PAGES: WebsitePageConfig[] = [
  {
    id: 'home',
    name: 'Home Page',
    slug: '/',
    livePath: '/',
    description: 'Peers Global homepage featuring ambient hero background, who we are boardroom banner, cyber earth network, leadership showcase, and impact reels.',
    sections: [
      {
        id: 'home-hero',
        name: 'Hero Background Header',
        subRoute: '/',
        description: 'Cinematic full-bleed 4K ambient video showing Indian promoters collaborating with world globe backdrops.',
        defaultMediaUrl: '/videos/hero-background.mp4',
        defaultSourceType: 'localhost',
        defaultTitle: 'Peers Global Grand Launch & Conclave Reel',
        subModules: [
          {
            id: 'sub-home-hero-bg',
            name: 'HERO AMBIENT REEL',
            eyebrow: 'HERO AMBIENT REEL',
            title: '4K Full-Bleed Earth & Atmosphere Reel',
            description: 'Main landing backdrop video with smooth cinematic transitions.',
            defaultMediaUrl: '/videos/hero-background.mp4',
            defaultSourceType: 'localhost',
            defaultTitle: 'Peers Global Grand Launch & Conclave Reel',
          },
        ],
      },
      {
        id: 'home-who-we-are',
        name: 'Section Banner Media (Who We Are)',
        subRoute: '/',
        description: 'Boardroom video loop with soft misty gradient fade on the left.',
        defaultMediaUrl: '/videos/homepage-hero-bg.mp4',
        defaultSourceType: 'localhost',
        defaultTitle: 'Who We Are — Collaborative Boardroom Story',
        subModules: [
          {
            id: 'sub-home-who-we-are',
            name: 'BOARDROOM STORY',
            eyebrow: 'BOARDROOM STORY',
            title: 'Collaborative Boardroom Video Loop',
            description: 'Curtain-reveal video loop displaying leadership and peer discussions.',
            defaultMediaUrl: '/videos/homepage-hero-bg.mp4',
            defaultSourceType: 'localhost',
            defaultTitle: 'Who We Are — Collaborative Boardroom Story',
          },
        ],
      },
      {
        id: 'home-cyber-earth',
        name: 'Cyber Earth Network (Mission Section)',
        subRoute: '/',
        description: 'High tech globe constellation video loop in the background of the Mission & Purpose section.',
        defaultMediaUrl: '/videos/peers-global-earth-loop.mp4',
        defaultSourceType: 'localhost',
        defaultTitle: 'Global Cyber Earth Network Loop',
        subModules: [
          {
            id: 'sub-home-earth',
            name: 'GLOBAL CONSTELLATION',
            eyebrow: 'GLOBAL CONSTELLATION',
            title: 'Interactive Globe & Cyber Network',
            description: 'Looping network globe showcasing 11+ Indian cities connected with global hubs.',
            defaultMediaUrl: '/videos/peers-global-earth-loop.mp4',
            defaultSourceType: 'localhost',
            defaultTitle: 'Global Cyber Earth Network Loop',
          },
        ],
      },
      {
        id: 'home-leadership',
        name: 'Featured Video Modal (Leadership Showcase)',
        subRoute: '/',
        description: 'Video backdrop for the Circle Founders and National Governing Council highlight.',
        defaultMediaUrl: '/videos/leadership-hero-bg.mp4',
        defaultSourceType: 'localhost',
        defaultTitle: 'Leadership & Circle Founders Overview',
        subModules: [
          {
            id: 'sub-home-leadership',
            name: 'GOVERNING COUNCIL',
            eyebrow: 'GOVERNING COUNCIL',
            title: 'Leadership & Circle Founders Overview',
            description: 'Featured video modal triggered from leadership card clicks.',
            defaultMediaUrl: '/videos/leadership-hero-bg.mp4',
            defaultSourceType: 'localhost',
            defaultTitle: 'Leadership & Circle Founders Overview',
          },
        ],
      },
      {
        id: 'home-testimonials',
        name: 'Story & Impact Reel (Video Testimonials)',
        subRoute: '/',
        description: 'Featured member growth stories and collaboration milestone highlights.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Member Testimonial & Value Reel',
        subModules: [
          {
            id: 'sub-home-testimonials',
            name: 'MEMBER TESTIMONIALS',
            eyebrow: 'MEMBER TESTIMONIALS',
            title: 'Member Growth Stories & Verified Outcomes',
            description: 'Curated video testimonials from active circle members.',
            defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            defaultSourceType: 'url',
            defaultTitle: 'Member Testimonial & Value Reel',
          },
        ],
      },
      {
        id: 'home-footer',
        name: 'Footer Video Bar',
        subRoute: '/',
        description: 'Subtle ambient video loop for the call-to-action invitation footer bar.',
        defaultMediaUrl: '/videos/hero-background.mp4',
        defaultSourceType: 'localhost',
        defaultTitle: 'Peers Global Community Invitation Video',
        subModules: [
          {
            id: 'sub-home-footer',
            name: 'COMMUNITY INVITATION',
            eyebrow: 'COMMUNITY INVITATION',
            title: 'Closing Call to Action Video Loop',
            description: 'Subtle motion loop behind the application footer bar.',
            defaultMediaUrl: '/videos/hero-background.mp4',
            defaultSourceType: 'localhost',
            defaultTitle: 'Peers Global Community Invitation Video',
          },
        ],
      },
    ],
  },
  {
    id: 'our-world',
    name: 'Our World',
    slug: '/the-idea',
    livePath: '/the-idea',
    description: 'Our World directory containing the founding manifesto, 10 Forms of Collaboration, and core philosophy.',
    sections: [
      {
        id: 'our-world-the-idea',
        name: 'The Idea',
        subRoute: '/the-idea',
        description: 'The founding manifesto and core belief of non-competitive structured peer networking.',
        defaultMediaUrl: '/videos/leadership-hero-bg.mp4',
        defaultSourceType: 'localhost',
        defaultTitle: 'The Idea — Founding Manifesto Video',
        subModules: [
          {
            id: 'sub-our-world-the-idea-hero-1',
            name: 'HERO COLLAGE — TOP LEFT (BOARDROOM)',
            eyebrow: 'HERO COLLAGE',
            title: 'Top-Left Arched Video — Boardroom & Leadership Circle',
            description: 'Looping ambient video in the top-left arched collage shape.',
            defaultMediaUrl: '/videos/leadership-hero-bg.mp4',
            defaultSourceType: 'localhost',
            defaultTitle: 'Peers Boardroom & Leadership Circle Video',
          },
          {
            id: 'sub-our-world-the-idea-hero-2',
            name: 'HERO COLLAGE — TOP RIGHT (CONCLAVE)',
            eyebrow: 'HERO COLLAGE',
            title: 'Top-Right Pill Video — Grand Conclave & Stage',
            description: 'Looping ambient video in the top-right tall pill collage shape.',
            defaultMediaUrl: '/videos/hero-background.mp4',
            defaultSourceType: 'localhost',
            defaultTitle: 'Peers Global Grand Conclave Video',
          },
          {
            id: 'sub-our-world-the-idea-hero-3',
            name: 'HERO COLLAGE — BOTTOM LEFT (PARTNERS)',
            eyebrow: 'HERO COLLAGE',
            title: 'Bottom-Left Arched Video — Partners in Business & Friends',
            description: 'Looping ambient video in the bottom-left arched collage shape.',
            defaultMediaUrl: '/videos/homepage-hero-bg.mp4',
            defaultSourceType: 'localhost',
            defaultTitle: 'Partners in Business & Friends in Life Video',
          },
          {
            id: 'sub-our-world-the-idea-hero-4',
            name: 'HERO COLLAGE — BOTTOM RIGHT (CIRCLES)',
            eyebrow: 'HERO COLLAGE',
            title: 'Bottom-Right Rounded Video — Circles & Community Collaboration',
            description: 'Looping ambient video in the bottom-right semi-circle collage shape.',
            defaultMediaUrl: '/videos/stories-hero-bg.mp4',
            defaultSourceType: 'localhost',
            defaultTitle: 'Peers Circles Collaboration Video',
          },
          {
            id: 'sub-our-world-the-idea-silent-reality',
            name: 'THE SILENT REALITY',
            eyebrow: 'THE SILENT REALITY',
            title: 'The problem nobody talks about.',
            description: 'Left visual video card and floating badges showcasing the unspoken challenges of entrepreneurs.',
            defaultMediaUrl: '/videos/leadership-hero-bg.mp4',
            defaultSourceType: 'localhost',
            defaultTitle: 'The Silent Reality — The Problem Nobody Talks About',
          },
          {
            id: 'sub-our-world-the-idea-origin-story',
            name: 'ORIGIN STORY',
            eyebrow: 'ORIGIN STORY',
            title: 'Where this idea came from',
            description: 'Arched ambient background video and Founder Dr. Pravin Parmar 2-minute message video.',
            defaultMediaUrl: '/videos/homepage-hero-bg.mp4',
            defaultSourceType: 'localhost',
            defaultTitle: 'Origin Story — In the words of our Founder',
          },
          {
            id: 'sub-our-world-the-idea-core-philosophy',
            name: 'THE CORE PHILOSOPHY',
            eyebrow: 'THE CORE PHILOSOPHY',
            title: 'What we believe (4-Sentence Sequence)',
            description: 'Curved panoramic video banner on the right illustrating trust, relationship, and business growth.',
            defaultMediaUrl: '/videos/homepage-hero-bg.mp4',
            defaultSourceType: 'localhost',
            defaultTitle: 'The Core Philosophy — What We Believe',
          },
          {
            id: 'sub-our-world-the-idea-peers-partners',
            name: 'PEERS ARE PARTNERS',
            eyebrow: 'PEERS ARE PARTNERS',
            title: 'Partners in business, friends in life',
            description: 'Featured hero video card highlighting genuine peer companionship.',
            defaultMediaUrl: '/videos/homepage-hero-bg.mp4',
            defaultSourceType: 'localhost',
            defaultTitle: 'Peers are Partners in Business & Friends in Life',
          },
        ],
      },
      {
        id: 'our-world-10-forms',
        name: '10 Forms of Collaboration',
        subRoute: '/10-forms-of-collaboration',
        description: '10 structured forms of peer support, joint ventures, and capital alliances.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: '10 Forms of Collaboration Model Explained',
        subModules: [
          {
            id: 'sub-our-world-10-forms-advisory',
            name: 'PEER ADVISORY',
            eyebrow: 'PEER ADVISORY',
            title: 'Monthly Inner Board Reviews & Problem Solving',
            description: 'Structured advisory process between peer entrepreneurs.',
            defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            defaultSourceType: 'url',
            defaultTitle: 'Peer Advisory & Inner Board Mechanics',
          },
          {
            id: 'sub-our-world-10-forms-capital',
            name: 'CAPITAL & STRATEGY',
            eyebrow: 'CAPITAL & STRATEGY',
            title: 'Joint Ventures, Co-Investments & Strategic Alliances',
            description: 'Ecosystem capital deployment and shared deal flow.',
            defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            defaultSourceType: 'url',
            defaultTitle: 'Capital & Strategic Alliances in Action',
          },
        ],
      },
      {
        id: 'our-world-territory',
        name: 'The Territory',
        subRoute: '/the-territory',
        description: 'Local to global expansion: from city Circle to national and international scale.',
        defaultMediaUrl: '/videos/peers-global-earth-loop.mp4',
        defaultSourceType: 'localhost',
        defaultTitle: 'The Territory — Local to Global Ecosystem',
        subModules: [
          {
            id: 'sub-our-world-territory-local',
            name: 'LOCAL CHAPTERS',
            eyebrow: 'LOCAL CHAPTERS',
            title: 'City Circles Across Tier 1, 2, and 3 Hubs',
            description: 'Active chapter ecosystem maps and city meetups.',
            defaultMediaUrl: '/videos/peers-global-earth-loop.mp4',
            defaultSourceType: 'localhost',
            defaultTitle: 'Local Chapters & Urban Hubs',
          },
          {
            id: 'sub-our-world-territory-global',
            name: 'GLOBAL EXPANSION',
            eyebrow: 'GLOBAL EXPANSION',
            title: 'International Bilateral Trade Corridors',
            description: 'Connecting Indian promoters to Dubai, Singapore, and global capitals.',
            defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            defaultSourceType: 'url',
            defaultTitle: 'Global Expansion & International Hubs',
          },
        ],
      },
      {
        id: 'our-world-citizens',
        name: 'The Citizens',
        subRoute: '/the-citizens',
        description: 'The entrepreneurs and promoters who build and govern this community.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'The Citizens of Peers Global',
        subModules: [
          {
            id: 'sub-our-world-citizens-council',
            name: 'GOVERNING COUNCIL',
            eyebrow: 'GOVERNING COUNCIL',
            title: 'National Governing Board & Stewards',
            description: 'Profiles of prominent entrepreneurs leading community governance.',
            defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            defaultSourceType: 'url',
            defaultTitle: 'Governing Council Keynote',
          },
          {
            id: 'sub-our-world-citizens-founders',
            name: 'CIRCLE FOUNDERS',
            eyebrow: 'CIRCLE FOUNDERS',
            title: 'Founding Promoters & Architects',
            description: 'Ecosystem architects convening new chapters across Bharat.',
            defaultMediaUrl: '/videos/leadership-hero-bg.mp4',
            defaultSourceType: 'localhost',
            defaultTitle: 'Circle Founders in Action',
          },
        ],
      },
      {
        id: 'our-world-currency',
        name: 'The Currency',
        subRoute: '/the-currency',
        description: 'The Impact System: 1 Action = 1 Life Impacted referral economy.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'The Currency — The Impact Economy',
        subModules: [
          {
            id: 'sub-our-world-currency-impact',
            name: 'IMPACT SYSTEM',
            eyebrow: 'IMPACT SYSTEM',
            title: '1 Action = 1 Life Impacted referral economy',
            description: 'Visual animation explaining value creation without transactional fees.',
            defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            defaultSourceType: 'url',
            defaultTitle: 'The Impact Economy Explained',
          },
        ],
      },
      {
        id: 'our-world-language',
        name: 'The Language',
        subRoute: '/the-language',
        description: 'The vocabulary, lexicon, and give-first principle of Peers Global.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'The Language & Give-First Philosophy',
        subModules: [
          {
            id: 'sub-our-world-language-lexicon',
            name: 'GIVE FIRST LEXICON',
            eyebrow: 'GIVE FIRST LEXICON',
            title: 'The Vocabulary of Contribution',
            description: 'Key principles and language norms within peer circles.',
            defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            defaultSourceType: 'url',
            defaultTitle: 'Give First Lexicon Reel',
          },
        ],
      },
      {
        id: 'our-world-culture-code',
        name: 'Our Culture & Code',
        subRoute: '/culture-and-code',
        description: '6 commitments and rituals of conduct governing peer relationships.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Our Culture & Code of Conduct',
        subModules: [
          {
            id: 'sub-our-world-culture-commitments',
            name: 'SIX COMMITMENTS',
            eyebrow: 'SIX COMMITMENTS',
            title: 'Non-Negotiable Code of Conduct',
            description: 'The six foundational pillars of trust and mutual accountability.',
            defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            defaultSourceType: 'url',
            defaultTitle: 'Six Commitments Code of Conduct',
          },
        ],
      },
      {
        id: 'our-world-1-million-mission',
        name: 'The 1 Million Mission',
        subRoute: '/1-million-mission',
        description: '1M+ entrepreneurs to impact by 2030 across Bharat and global hubs.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'The 1 Million Entrepreneurs Mission by 2030',
        subModules: [
          {
            id: 'sub-our-world-mission-2030',
            name: 'MISSION 2030',
            eyebrow: 'MISSION 2030',
            title: 'Empowering 1,000,000 Promoters by 2030',
            description: 'Roadmap and national campaign for MSME promoter transformation.',
            defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            defaultSourceType: 'url',
            defaultTitle: 'Mission 2030 Vision Reel',
          },
        ],
      },
    ],
  },
  {
    id: 'circles',
    name: 'Circles',
    slug: '/circles',
    livePath: '/circles',
    description: 'Circles directory containing 18 industry and goal-specific peer circles with category exclusivity.',
    sections: [
      {
        id: 'circles-all',
        name: 'All Circles',
        subRoute: '/circles',
        description: '18 industry and goal-specific Circles with locked seat exclusivity.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'All Governed Circles Overview',
        subModules: [
          {
            id: 'sub-circles-overview',
            name: 'GOVERNED CIRCLES OVERVIEW',
            eyebrow: 'GOVERNED CIRCLES OVERVIEW',
            title: '18 Industry & Purpose Circles',
            description: 'Overview video of exclusive seat governance.',
            defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            defaultSourceType: 'url',
            defaultTitle: 'Governed Circles Overview Reel',
          },
        ],
      },
      {
        id: 'circles-industry',
        name: 'Browse by Industry',
        subRoute: '/circles/industry',
        description: '9 sector-locked industry Circles preventing internal competition.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Industry Specific Circles Directory',
        subModules: [
          {
            id: 'sub-circles-industry-sectors',
            name: 'INDUSTRY SECTOR HUBS',
            eyebrow: 'INDUSTRY SECTOR HUBS',
            title: 'Manufacturing, Tech, Healthcare, Retail',
            description: 'Industry-specific peer groups.',
            defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            defaultSourceType: 'url',
            defaultTitle: 'Industry Sector Hubs Showcase',
          },
        ],
      },
      {
        id: 'circles-purpose',
        name: 'Browse by Purpose',
        subRoute: '/circles/purpose',
        description: '10 shared-ambition goal Circles for fast growth scaling.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Purpose & Growth Driven Circles',
      },
      {
        id: 'circles-find',
        name: 'Find Your Circle',
        subRoute: '/circles/find',
        description: 'Match with your ideal Circle and Inner Board based on category and city.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Circle Matching & Inner Board Experience',
      },
      {
        id: 'circles-meeting-experience',
        name: 'The Circle Meeting Experience',
        subRoute: '/circle-meeting-experience',
        description: '4-part monthly 150-minute governed meeting structure.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Inside the 150-Minute Governed Circle Meeting',
        subModules: [
          {
            id: 'sub-circles-meeting-protocol',
            name: '150-MINUTE MEETING PROTOCOL',
            eyebrow: '150-MINUTE MEETING PROTOCOL',
            title: 'Inside the Governed Circle Meeting',
            description: 'Video walk-through of the 4-part agenda and hot seat format.',
            defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            defaultSourceType: 'url',
            defaultTitle: 'Governed Circle Meeting Protocol Video',
          },
        ],
      },
      {
        id: 'circles-start',
        name: 'Start a Circle',
        subRoute: '/start-a-circle',
        description: 'Convene and launch a new Circle chapter from Day 1 in your city.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'How to Start a Circle in Your Region',
      },
      {
        id: 'circles-map',
        name: 'Circle Map — Cities & Countries',
        subRoute: '/map',
        description: 'Live interactive map of active chapters across 11+ Indian cities.',
        defaultMediaUrl: '/videos/peers-global-earth-loop.mp4',
        defaultSourceType: 'localhost',
        defaultTitle: 'Peers Global Chapters & Geographic Footprint',
      },
    ],
  },
  {
    id: 'membership',
    name: 'Membership',
    slug: '/membership',
    livePath: '/membership',
    description: 'Membership directory detailing membership standing, fee tiers, benefits, and application process.',
    sections: [
      {
        id: 'membership-why-join',
        name: 'Why Join',
        subRoute: '/membership',
        description: 'Why your next breakthrough won’t come alone: the power of curated peer boards.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Why Join Peers Global — The Value Proposition',
        subModules: [
          {
            id: 'sub-membership-value-prop',
            name: 'VALUE PROPOSITION',
            eyebrow: 'VALUE PROPOSITION',
            title: 'Why Your Next Breakthrough Won’t Come Alone',
            description: 'The core reason for joining a governed peer board.',
            defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            defaultSourceType: 'url',
            defaultTitle: 'Why Join Peers Global Video',
          },
        ],
      },
      {
        id: 'membership-who-belongs',
        name: 'Who Belongs Here',
        subRoute: '/who-belongs-here',
        description: 'The fifteen names test, candidate curation fit, and promoter ethics.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Who Belongs in Peers Global — Candidate Fit',
      },
      {
        id: 'membership-tiers',
        name: 'Compare Tiers',
        subRoute: '/membership/tiers',
        description: 'Full fee transparency and ₹2L+ annual delivered value breakdown.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Membership Tiers & Transparent ROI Comparison',
      },
      {
        id: 'membership-criteria',
        name: 'Criteria & Process',
        subRoute: '/membership/criteria',
        description: '2-step application process and Circle Director board approval.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Admission Criteria & Review Process',
      },
      {
        id: 'membership-benefits',
        name: 'What You Get',
        subRoute: '/membership/benefits',
        description: 'Complete annual calendar, conclave passes, and circle inclusions.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Comprehensive Membership Benefits & Deliverables',
      },
      {
        id: 'membership-faq',
        name: 'Member FAQ',
        subRoute: '/membership/faq',
        description: 'All 10 confirmed question categories answered by leadership.',
        defaultMediaUrl: '/videos/stories-hero-bg.mp4',
        defaultSourceType: 'localhost',
        defaultTitle: 'Frequently Asked Questions by Prospective Members',
        subModules: [
          {
            id: 'sub-membership-faq',
            name: 'MEMBER FAQ HERO',
            eyebrow: 'MEMBERSHIP',
            title: 'Member FAQ',
            description: 'Main hero ambient video loop for Member FAQ page.',
            defaultMediaUrl: '/videos/stories-hero-bg.mp4',
            defaultSourceType: 'localhost',
            defaultTitle: 'Frequently Asked Questions by Prospective Members',
          },
        ],
      },
      {
        id: 'membership-apply',
        name: 'Apply',
        subRoute: '/apply',
        description: 'Begin your journey through the application and onboarding funnel.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Apply for Peers Global Membership',
      },
    ],
  },
  {
    id: 'leadership',
    name: 'Leadership',
    slug: '/leadership',
    livePath: '/leadership',
    description: 'Leadership directory containing pathway from Member to ecosystem owner, Circle Founder to Governing Council.',
    sections: [
      {
        id: 'leadership-ladder',
        name: 'The Leadership Ladder',
        subRoute: '/leadership',
        description: 'Pathway from Member to ecosystem owner across Bharat and beyond.',
        defaultMediaUrl: '/videos/leadership-hero-bg.mp4',
        defaultSourceType: 'localhost',
        defaultTitle: 'The Leadership Ladder & Governance Structure',
        subModules: [
          {
            id: 'sub-leadership-pathway',
            name: 'LEADERSHIP PATHWAY',
            eyebrow: 'LEADERSHIP PATHWAY',
            title: 'From Member to Ecosystem Steward',
            description: 'The tiered roles and responsibilities in the governance framework.',
            defaultMediaUrl: '/videos/leadership-hero-bg.mp4',
            defaultSourceType: 'localhost',
            defaultTitle: 'The Leadership Ladder Overview',
          },
        ],
      },
      {
        id: 'leadership-circle-founder',
        name: 'Circle Founder',
        subRoute: '/leadership/circle-founder',
        description: 'Convene and launch new Circles as a founding community architect.',
        defaultMediaUrl: '/videos/hero-background.mp4',
        defaultSourceType: 'localhost',
        defaultTitle: 'Circle Founder Role, Economics & Impact',
        subModules: [
          {
            id: 'sub-leadership-circle-founder',
            name: 'CIRCLE FOUNDER HERO',
            eyebrow: 'FLAGSHIP ROLE',
            title: 'Leading the leaders.',
            description: 'Main hero ambient video loop for Circle Founder role.',
            defaultMediaUrl: '/videos/hero-background.mp4',
            defaultSourceType: 'localhost',
            defaultTitle: 'Circle Founder Role, Economics & Impact',
          },
        ],
      },
      {
        id: 'leadership-circle-director',
        name: 'Circle Director',
        subRoute: '/leadership/circle-director',
        description: 'Runs and moderates the Circle month on month with structured governance.',
        defaultMediaUrl: '/videos/stories-hero-bg.mp4',
        defaultSourceType: 'localhost',
        defaultTitle: 'Circle Director Leadership & Meeting Stewardship',
        subModules: [
          {
            id: 'sub-leadership-circle-director',
            name: 'CIRCLE DIRECTOR HERO',
            eyebrow: 'LEADERSHIP',
            title: 'You grow the Circle, and everyone in it.',
            description: 'Main hero ambient video loop for Circle Director role.',
            defaultMediaUrl: '/videos/stories-hero-bg.mp4',
            defaultSourceType: 'localhost',
            defaultTitle: 'Circle Director Leadership & Meeting Stewardship',
          },
        ],
      },
      {
        id: 'leadership-industry-director',
        name: 'Industry Director',
        subRoute: '/leadership/industry-director',
        description: 'Sector ecosystem owner for the city coordinating industry clusters.',
        defaultMediaUrl: '/videos/global-earth-hd.mp4',
        defaultSourceType: 'localhost',
        defaultTitle: 'Industry Director Ecosystem Role',
        subModules: [
          {
            id: 'sub-leadership-industry-director',
            name: 'INDUSTRY DIRECTOR HERO',
            eyebrow: 'LEADERSHIP',
            title: 'You carry an industry.',
            description: 'Main hero ambient video loop for Industry Director role.',
            defaultMediaUrl: '/videos/global-earth-hd.mp4',
            defaultSourceType: 'localhost',
            defaultTitle: 'Industry Director Ecosystem Role',
          },
        ],
      },
      {
        id: 'leadership-executive-director',
        name: 'Executive Director',
        subRoute: '/leadership/executive-director',
        description: 'Area, District, State, and Country leadership steward.',
        defaultMediaUrl: '/videos/homepage-hero-bg.mp4',
        defaultSourceType: 'localhost',
        defaultTitle: 'Executive Director Regional Leadership',
        subModules: [
          {
            id: 'sub-leadership-executive-director',
            name: 'EXECUTIVE DIRECTOR HERO',
            eyebrow: 'LEADERSHIP',
            title: 'You carry territory.',
            description: 'Main hero ambient video loop for Executive Director role.',
            defaultMediaUrl: '/videos/homepage-hero-bg.mp4',
            defaultSourceType: 'localhost',
            defaultTitle: 'Executive Director Regional Leadership',
          },
        ],
      },
      {
        id: 'leadership-global-advisors',
        name: 'Global Advisory Board',
        subRoute: '/leadership/global-advisors',
        description: 'Senior entrepreneurs and industry veterans guiding the movement.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Global Advisory Board Keynote',
      },
      {
        id: 'leadership-ambassador',
        name: 'Ambassador',
        subRoute: '/leadership/ambassadors',
        description: 'You carry the name. Discover the Ambassador appointment at Peers Global.',
        defaultMediaUrl: '/videos/journey-bg.mp4',
        defaultSourceType: 'localhost',
        defaultTitle: 'Ambassador Leadership Role & Stature',
        subModules: [
          {
            id: 'sub-leadership-ambassador',
            name: 'AMBASSADOR HERO',
            eyebrow: 'LEADERSHIP',
            title: 'You carry the name.',
            description: 'Main hero ambient video loop for Ambassador role.',
            defaultMediaUrl: '/videos/journey-bg.mp4',
            defaultSourceType: 'localhost',
            defaultTitle: 'Ambassador Leadership Role & Stature',
          },
        ],
      },
      {
        id: 'leadership-powerhouse',
        name: 'The Powerhouse',
        subRoute: '/leadership/powerhouse',
        description: 'The leadership team of a Circle — 3 committees, 3 chairs, 9 leaders.',
        defaultMediaUrl: '/videos/leadership-hero-bg.mp4',
        defaultSourceType: 'localhost',
        defaultTitle: 'The Powerhouse Leadership Team Meeting',
        subModules: [
          {
            id: 'sub-leadership-powerhouse',
            name: 'POWERHOUSE HERO',
            eyebrow: 'LEADERSHIP',
            title: 'The leadership team of a Circle.',
            description: 'Main hero ambient video loop for Powerhouse role.',
            defaultMediaUrl: '/videos/leadership-hero-bg.mp4',
            defaultSourceType: 'localhost',
            defaultTitle: 'The Powerhouse Leadership Team Meeting',
          },
        ],
      },
      {
        id: 'leadership-apply-to-lead',
        name: 'Apply to Lead',
        subRoute: '/leadership/apply',
        description: 'Submit expression of interest for leadership positions.',
        defaultMediaUrl: '/videos/leadership-hero-bg.mp4',
        defaultSourceType: 'localhost',
        defaultTitle: 'Leadership Application & Vetting Overview',
        subModules: [
          {
            id: 'sub-leadership-apply-to-lead',
            name: 'APPLY TO LEAD HERO',
            eyebrow: 'LEADERSHIP',
            title: 'Every leadership role begins with a conversation.',
            description: 'Main hero ambient video loop for Apply to Lead page.',
            defaultMediaUrl: '/videos/leadership-hero-bg.mp4',
            defaultSourceType: 'localhost',
            defaultTitle: 'Leadership Application & Vetting Overview',
          },
        ],
      },
    ],
  },
  {
    id: 'unity',
    name: 'Unity',
    slug: '/unity',
    livePath: '/unity',
    description: 'Unity directory detailing the mobile application, direct chat, peer discovery, and meeting tools.',
    sections: [
      {
        id: 'unity-app-walkthrough',
        name: 'Unity App Walkthrough',
        subRoute: '/unity',
        description: 'Mobile screen recording displaying peer discovery and direct messaging.',
        defaultMediaUrl: '/videos/unity-demo.mp4',
        defaultSourceType: 'localhost',
        defaultTitle: 'Unity App UI Walkthrough & Peer Discovery',
        subModules: [
          {
            id: 'sub-unity-walkthrough',
            name: 'APP UI WALKTHROUGH',
            eyebrow: 'APP UI WALKTHROUGH',
            title: 'Native Mobile App Demo & Direct Chat',
            description: 'Interactive walkthrough of the iOS and Android Unity app.',
            defaultMediaUrl: '/videos/unity-demo.mp4',
            defaultSourceType: 'localhost',
            defaultTitle: 'Unity App UI Walkthrough',
          },
        ],
      },
      {
        id: 'unity-peer-discovery',
        name: 'Peer Discovery & Direct Chat',
        subRoute: '/unity/peers',
        description: 'How members connect directly across categories and cities securely.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Peer Discovery & Real-Time Messaging Demo',
      },
      {
        id: 'unity-onboarding',
        name: 'Mobile Experience & Onboarding',
        subRoute: '/unity/onboarding',
        description: 'Speed showcase of hot-seat voting, meeting reminders, and circle directories.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Unity App Onboarding & Mobile Feature Reel',
      },
    ],
  },
  {
    id: 'community-life',
    name: 'Community Life',
    slug: '/events',
    livePath: '/events',
    description: 'Community Life directory containing events, conclaves, peer stories, collaboration wins, and media.',
    sections: [
      {
        id: 'community-events-summits',
        name: 'Events & Summits',
        subRoute: '/events',
        description: 'Monthly meetings, national conclaves, retreats, and annual summits.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Peers Global Conclaves & Summits Reel',
        subModules: [
          {
            id: 'sub-community-conclaves',
            name: 'NATIONAL CONCLAVES',
            eyebrow: 'NATIONAL CONCLAVES',
            title: 'Annual Conclaves & Chapter Summits',
            description: 'Highlights from flagship annual summits and award ceremonies.',
            defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            defaultSourceType: 'url',
            defaultTitle: 'National Conclaves Reel',
          },
        ],
      },
      {
        id: 'community-peer-stories',
        name: 'Peer Stories',
        subRoute: '/stories',
        description: 'Named Peers, verified numbers, and real business outcome stories.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Verified Peer Outcome Stories',
      },
      {
        id: 'community-collaboration-wins',
        name: 'Collaboration Wins',
        subRoute: '/stories/wins',
        description: 'Live feed of confirmed peer actions and joint venture transactions.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Collaboration Wins & Impact Highlights',
      },
      {
        id: 'community-blog-insights',
        name: 'Blog & Insights',
        subRoute: '/insights',
        description: 'Written and recorded by entrepreneurs who built scaling companies.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Peers Insights & Thought Leadership',
      },
      {
        id: 'community-awards',
        name: 'Awards & Recognition',
        subRoute: '/awards',
        description: 'Recognising public contribution and collaboration milestones.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'National Peer Awards & Honors Reel',
      },
      {
        id: 'community-gallery',
        name: 'Gallery',
        subRoute: '/gallery',
        description: 'Moments from conclaves, conclave halls, and Circle meetings.',
        defaultMediaUrl: '/videos/hero-background.mp4',
        defaultSourceType: 'localhost',
        defaultTitle: 'Conclave & Circle Meeting Gallery Reel',
      },
      {
        id: 'community-podcast-media',
        name: 'Podcast & Media',
        subRoute: '/media',
        description: 'Peers Candid Talks, TV features, and press coverage.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Peers Candid Talks Podcast & Press Reel',
      },
    ],
  },
  {
    id: 'about',
    name: 'About',
    slug: '/founder',
    livePath: '/founder',
    description: 'About directory detailing our origin story, Dr. Pravin Parmar (Founder), contact, and initiatives.',
    sections: [
      {
        id: 'about-our-story',
        name: 'Our Story',
        subRoute: '/our-story',
        description: 'From a hospital corridor to 1M mission: the origin story of Peers Global.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Our Story — From Hospital Corridor to 1M Mission',
        subModules: [
          {
            id: 'sub-about-our-story-origin',
            name: 'THE BOTAD AWAKENING',
            eyebrow: 'THE BOTAD AWAKENING',
            title: 'From Hospital Corridor to 1M Mission',
            description: 'The deeply personal founding story of Peers Global.',
            defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            defaultSourceType: 'url',
            defaultTitle: 'The Botad Awakening Video',
          },
        ],
      },
      {
        id: 'about-founder',
        name: 'Dr. Pravin Parmar (Founder)',
        subRoute: '/founder',
        description: 'Founder keynote address, background, and vision of Dr. Pravin Parmar.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Dr. Pravin Parmar Founder Keynote Address',
        subModules: [
          {
            id: 'sub-about-founder-keynote',
            name: 'FOUNDER KEYNOTE',
            eyebrow: 'FOUNDER KEYNOTE',
            title: 'Dr. Pravin Parmar Keynote Address',
            description: 'Full video message from the Founder.',
            defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            defaultSourceType: 'url',
            defaultTitle: 'Dr. Pravin Parmar Founder Keynote Address',
          },
        ],
      },
      {
        id: 'about-contact',
        name: 'Contact',
        subRoute: '/contact',
        description: 'Direct routing and corporate headquarters communication center.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Peers Global Corporate Headquarters & Support',
      },
      {
        id: 'about-initiatives',
        name: 'Our Initiatives',
        subRoute: '/initiatives',
        description: 'VyapaarJagat, Fempreneur & Greenpreneur ecosystem platforms.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Ecosystem Initiatives & National Platforms',
      },
      {
        id: 'about-foundation',
        name: 'Foundation & Social Impact',
        subRoute: '/foundation',
        description: 'Section 8 foundation and evidenced social development goals.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Foundation & Social Impact Programs',
      },
      {
        id: 'about-newsroom',
        name: 'Newsroom',
        subRoute: '/newsroom',
        description: 'Press releases, media coverage, and downloadable brand assets.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Peers Global Press & Media Newsroom',
      },
      {
        id: 'about-partner',
        name: 'Partner With Us',
        subRoute: '/partner-with-us',
        description: 'Institutional partnerships and corporate alliances.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Institutional & Corporate Partnerships',
      },
      {
        id: 'about-investors',
        name: 'Investors',
        subRoute: '/investors',
        description: 'Pre-Series A institutional overview and growth projections.',
        defaultMediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        defaultSourceType: 'url',
        defaultTitle: 'Investor Overview & Scale Strategy',
      },
    ],
  },
]

export const INITIAL_PAGE_MEDIA: PageMediaItem[] = [
  // Home Page Videos
  {
    id: 'pm-home-1',
    pageId: 'home',
    pageName: 'Home Page',
    pageSlug: '/',
    sectionId: 'home-hero',
    sectionName: 'Hero Background Header',
    subModuleId: 'sub-home-hero-bg',
    subModuleName: 'HERO AMBIENT REEL',
    title: 'Peers Global Grand Launch & Conclave Reel',
    description: 'High energy ambient background video showing Indian promoters collaborating.',
    mediaType: 'video',
    sourceType: 'localhost',
    mediaUrl: '/videos/hero-background.mp4',
    isActive: true,
    createdAt: '2026-08-01',
  },
  {
    id: 'pm-home-2',
    pageId: 'home',
    pageName: 'Home Page',
    pageSlug: '/',
    sectionId: 'home-who-we-are',
    sectionName: 'Section Banner Media (Who We Are)',
    subModuleId: 'sub-home-who-we-are',
    subModuleName: 'BOARDROOM STORY',
    title: 'Who We Are — Collaborative Boardroom Story',
    description: 'Boardroom video loop with soft misty gradient fade on the left.',
    mediaType: 'video',
    sourceType: 'localhost',
    mediaUrl: '/videos/homepage-hero-bg.mp4',
    isActive: true,
    createdAt: '2026-08-05',
  },
  {
    id: 'pm-home-3',
    pageId: 'home',
    pageName: 'Home Page',
    pageSlug: '/',
    sectionId: 'home-cyber-earth',
    sectionName: 'Cyber Earth Network (Mission Section)',
    subModuleId: 'sub-home-earth',
    subModuleName: 'GLOBAL CONSTELLATION',
    title: 'Global Cyber Earth Network Loop',
    description: 'High tech globe constellation video loop in the background of the Mission & Purpose section.',
    mediaType: 'video',
    sourceType: 'localhost',
    mediaUrl: '/videos/peers-global-earth-loop.mp4',
    isActive: true,
    createdAt: '2026-08-08',
  },
  {
    id: 'pm-home-4',
    pageId: 'home',
    pageName: 'Home Page',
    pageSlug: '/',
    sectionId: 'home-leadership',
    sectionName: 'Featured Video Modal (Leadership Showcase)',
    subModuleId: 'sub-home-leadership',
    subModuleName: 'GOVERNING COUNCIL',
    title: 'Leadership & Circle Founders Overview',
    description: 'Video backdrop for the Circle Founders and National Governing Council highlight.',
    mediaType: 'video',
    sourceType: 'localhost',
    mediaUrl: '/videos/leadership-hero-bg.mp4',
    isActive: true,
    createdAt: '2026-08-10',
  },
  {
    id: 'pm-home-5',
    pageId: 'home',
    pageName: 'Home Page',
    pageSlug: '/',
    sectionId: 'home-testimonials',
    sectionName: 'Story & Impact Reel (Video Testimonials)',
    subModuleId: 'sub-home-testimonials',
    subModuleName: 'MEMBER TESTIMONIALS',
    title: 'Member Testimonial & Value Reel',
    description: 'Featured member growth stories and collaboration milestone highlights.',
    mediaType: 'video',
    sourceType: 'url',
    mediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    isActive: true,
    createdAt: '2026-08-12',
  },
  {
    id: 'pm-home-6',
    pageId: 'home',
    pageName: 'Home Page',
    pageSlug: '/',
    sectionId: 'home-footer',
    sectionName: 'Footer Video Bar',
    subModuleId: 'sub-home-footer',
    subModuleName: 'COMMUNITY INVITATION',
    title: 'Peers Global Community Invitation Video',
    description: 'Subtle ambient video loop for the call-to-action invitation footer bar.',
    mediaType: 'video',
    sourceType: 'localhost',
    mediaUrl: '/videos/hero-background.mp4',
    isActive: true,
    createdAt: '2026-08-15',
  },

  // Our World (/the-idea) Sub-Modules (Matches Screenshots 1, 3, 4, 5)
  {
    id: 'pm-our-world-hero-1',
    pageId: 'our-world',
    pageName: 'Our World',
    pageSlug: '/the-idea',
    sectionId: 'our-world-the-idea',
    sectionName: 'The Idea',
    subModuleId: 'sub-our-world-the-idea-hero-1',
    subModuleName: 'HERO COLLAGE — TOP LEFT (BOARDROOM)',
    title: 'Peers Boardroom & Leadership Circle Video',
    description: 'Looping ambient video in the top-left arched collage shape.',
    mediaType: 'video',
    sourceType: 'localhost',
    mediaUrl: '/videos/leadership-hero-bg.mp4',
    isActive: true,
    createdAt: '2026-08-01',
  },
  {
    id: 'pm-our-world-hero-2',
    pageId: 'our-world',
    pageName: 'Our World',
    pageSlug: '/the-idea',
    sectionId: 'our-world-the-idea',
    sectionName: 'The Idea',
    subModuleId: 'sub-our-world-the-idea-hero-2',
    subModuleName: 'HERO COLLAGE — TOP RIGHT (CONCLAVE)',
    title: 'Peers Global Grand Conclave Video',
    description: 'Looping ambient video in the top-right tall pill collage shape.',
    mediaType: 'video',
    sourceType: 'localhost',
    mediaUrl: '/videos/hero-background.mp4',
    isActive: true,
    createdAt: '2026-08-01',
  },
  {
    id: 'pm-our-world-hero-3',
    pageId: 'our-world',
    pageName: 'Our World',
    pageSlug: '/the-idea',
    sectionId: 'our-world-the-idea',
    sectionName: 'The Idea',
    subModuleId: 'sub-our-world-the-idea-hero-3',
    subModuleName: 'HERO COLLAGE — BOTTOM LEFT (PARTNERS)',
    title: 'Partners in Business & Friends in Life Video',
    description: 'Looping cyber network video in the bottom-left arched collage shape.',
    mediaType: 'video',
    sourceType: 'localhost',
    mediaUrl: '/videos/peers-global-earth-loop.mp4',
    isActive: true,
    createdAt: '2026-08-01',
  },
  {
    id: 'pm-our-world-hero-4',
    pageId: 'our-world',
    pageName: 'Our World',
    pageSlug: '/the-idea',
    sectionId: 'our-world-the-idea',
    sectionName: 'The Idea',
    subModuleId: 'sub-our-world-the-idea-hero-4',
    subModuleName: 'HERO COLLAGE — BOTTOM RIGHT (CIRCLES)',
    title: 'Peers Circles Collaboration Video',
    description: 'Looping community stories video in the bottom-right semi-circle collage shape.',
    mediaType: 'video',
    sourceType: 'localhost',
    mediaUrl: '/videos/stories-hero-bg.mp4',
    isActive: true,
    createdAt: '2026-08-01',
  },
  {
    id: 'pm-our-world-silent-reality',
    pageId: 'our-world',
    pageName: 'Our World',
    pageSlug: '/the-idea',
    sectionId: 'our-world-the-idea',
    sectionName: 'The Idea',
    subModuleId: 'sub-our-world-the-idea-silent-reality',
    subModuleName: 'THE SILENT REALITY',
    title: 'The Silent Reality — The Problem Nobody Talks About',
    description: 'Left visual video card and floating badges showcasing the unspoken challenges of entrepreneurs.',
    mediaType: 'video',
    sourceType: 'localhost',
    mediaUrl: '/videos/leadership-hero-bg.mp4',
    isActive: true,
    createdAt: '2026-08-01',
  },
  {
    id: 'pm-our-world-origin-story',
    pageId: 'our-world',
    pageName: 'Our World',
    pageSlug: '/the-idea',
    sectionId: 'our-world-the-idea',
    sectionName: 'The Idea',
    subModuleId: 'sub-our-world-the-idea-origin-story',
    subModuleName: 'ORIGIN STORY',
    title: 'Origin Story — In the words of our Founder',
    description: 'Arched ambient background video and Founder Dr. Pravin Parmar 2-minute message video.',
    mediaType: 'video',
    sourceType: 'localhost',
    mediaUrl: '/videos/homepage-hero-bg.mp4',
    isActive: true,
    createdAt: '2026-08-01',
  },
  {
    id: 'pm-our-world-core-philosophy',
    pageId: 'our-world',
    pageName: 'Our World',
    pageSlug: '/the-idea',
    sectionId: 'our-world-the-idea',
    sectionName: 'The Idea',
    subModuleId: 'sub-our-world-the-idea-core-philosophy',
    subModuleName: 'THE CORE PHILOSOPHY',
    title: 'The Core Philosophy — What We Believe',
    description: 'Curved panoramic video banner on the right illustrating trust, relationship, and business growth.',
    mediaType: 'video',
    sourceType: 'localhost',
    mediaUrl: '/videos/homepage-hero-bg.mp4',
    isActive: true,
    createdAt: '2026-08-01',
  },
  {
    id: 'pm-our-world-peers-partners',
    pageId: 'our-world',
    pageName: 'Our World',
    pageSlug: '/the-idea',
    sectionId: 'our-world-the-idea',
    sectionName: 'The Idea',
    subModuleId: 'sub-our-world-the-idea-peers-partners',
    subModuleName: 'PEERS ARE PARTNERS',
    title: 'Peers are Partners in Business & Friends in Life',
    description: 'Featured hero video card highlighting genuine peer companionship.',
    mediaType: 'video',
    sourceType: 'localhost',
    mediaUrl: '/videos/homepage-hero-bg.mp4',
    isActive: true,
    createdAt: '2026-08-01',
  },

  // Other Our World sections
  {
    id: 'pm-our-world-10-forms',
    pageId: 'our-world',
    pageName: 'Our World',
    pageSlug: '/the-idea',
    sectionId: 'our-world-10-forms',
    sectionName: '10 Forms of Collaboration',
    subModuleId: 'sub-our-world-10-forms-advisory',
    subModuleName: 'PEER ADVISORY',
    title: '10 Forms of Collaboration Model Explained',
    description: '10 structured forms of peer support, joint ventures, and capital alliances.',
    mediaType: 'video',
    sourceType: 'url',
    mediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    isActive: true,
    createdAt: '2026-08-01',
  },
  {
    id: 'pm-our-world-territory',
    pageId: 'our-world',
    pageName: 'Our World',
    pageSlug: '/the-idea',
    sectionId: 'our-world-territory',
    sectionName: 'The Territory',
    subModuleId: 'sub-our-world-territory-local',
    subModuleName: 'LOCAL CHAPTERS',
    title: 'The Territory — Local to Global Ecosystem',
    description: 'Local to global expansion: from city Circle to national and international scale.',
    mediaType: 'video',
    sourceType: 'localhost',
    mediaUrl: '/videos/peers-global-earth-loop.mp4',
    isActive: true,
    createdAt: '2026-08-01',
  },
  {
    id: 'pm-our-world-citizens',
    pageId: 'our-world',
    pageName: 'Our World',
    pageSlug: '/the-idea',
    sectionId: 'our-world-citizens',
    sectionName: 'The Citizens',
    subModuleId: 'sub-our-world-citizens-council',
    subModuleName: 'GOVERNING COUNCIL',
    title: 'The Citizens of Peers Global',
    description: 'The entrepreneurs and promoters who build and govern this community.',
    mediaType: 'video',
    sourceType: 'url',
    mediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    isActive: true,
    createdAt: '2026-08-01',
  },
  {
    id: 'pm-our-world-currency',
    pageId: 'our-world',
    pageName: 'Our World',
    pageSlug: '/the-idea',
    sectionId: 'our-world-currency',
    sectionName: 'The Currency',
    subModuleId: 'sub-our-world-currency-impact',
    subModuleName: 'IMPACT SYSTEM',
    title: 'The Currency — The Impact Economy',
    description: 'The Impact System: 1 Action = 1 Life Impacted referral economy.',
    mediaType: 'video',
    sourceType: 'url',
    mediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    isActive: true,
    createdAt: '2026-08-01',
  },
  {
    id: 'pm-our-world-language',
    pageId: 'our-world',
    pageName: 'Our World',
    pageSlug: '/the-idea',
    sectionId: 'our-world-language',
    sectionName: 'The Language',
    subModuleId: 'sub-our-world-language-lexicon',
    subModuleName: 'GIVE FIRST LEXICON',
    title: 'The Language & Give-First Philosophy',
    description: 'The vocabulary, lexicon, and give-first principle of Peers Global.',
    mediaType: 'video',
    sourceType: 'url',
    mediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    isActive: true,
    createdAt: '2026-08-01',
  },
  {
    id: 'pm-our-world-culture',
    pageId: 'our-world',
    pageName: 'Our World',
    pageSlug: '/the-idea',
    sectionId: 'our-world-culture-code',
    sectionName: 'Our Culture & Code',
    subModuleId: 'sub-our-world-culture-commitments',
    subModuleName: 'SIX COMMITMENTS',
    title: 'Our Culture & Code of Conduct',
    description: '6 commitments and rituals of conduct governing peer relationships.',
    mediaType: 'video',
    sourceType: 'url',
    mediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    isActive: true,
    createdAt: '2026-08-01',
  },
  {
    id: 'pm-our-world-mission',
    pageId: 'our-world',
    pageName: 'Our World',
    pageSlug: '/the-idea',
    sectionId: 'our-world-1-million-mission',
    sectionName: 'The 1 Million Mission',
    subModuleId: 'sub-our-world-mission-2030',
    subModuleName: 'MISSION 2030',
    title: 'The 1 Million Entrepreneurs Mission by 2030',
    description: '1M+ entrepreneurs to impact by 2030 across Bharat and global hubs.',
    mediaType: 'video',
    sourceType: 'url',
    mediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    isActive: true,
    createdAt: '2026-08-01',
  },

  // Circles
  {
    id: 'pm-circles-1',
    pageId: 'circles',
    pageName: 'Circles',
    pageSlug: '/circles',
    sectionId: 'circles-all',
    sectionName: 'All Circles',
    subModuleId: 'sub-circles-overview',
    subModuleName: 'GOVERNED CIRCLES OVERVIEW',
    title: 'All Governed Circles Overview',
    description: '18 industry and goal-specific Circles with locked seat exclusivity.',
    mediaType: 'video',
    sourceType: 'url',
    mediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    isActive: true,
    createdAt: '2026-08-20',
  },

  // Membership
  {
    id: 'pm-membership-1',
    pageId: 'membership',
    pageName: 'Membership',
    pageSlug: '/membership',
    sectionId: 'membership-why-join',
    sectionName: 'Why Join',
    subModuleId: 'sub-membership-value-prop',
    subModuleName: 'VALUE PROPOSITION',
    title: 'Why Join Peers Global — The Value Proposition',
    description: 'Why your next breakthrough won’t come alone: the power of curated peer boards.',
    mediaType: 'video',
    sourceType: 'url',
    mediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    isActive: true,
    createdAt: '2026-08-10',
  },

  // Leadership
  {
    id: 'pm-leadership-1',
    pageId: 'leadership',
    pageName: 'Leadership',
    pageSlug: '/leadership',
    sectionId: 'leadership-ladder',
    sectionName: 'The Leadership Ladder',
    subModuleId: 'sub-leadership-pathway',
    subModuleName: 'LEADERSHIP PATHWAY',
    title: 'The Leadership Ladder & Governance Structure',
    description: 'Pathway from Member to ecosystem owner across Bharat and beyond.',
    mediaType: 'video',
    sourceType: 'localhost',
    mediaUrl: '/videos/leadership-hero-bg.mp4',
    isActive: true,
    createdAt: '2026-08-12',
  },

  // Unity
  {
    id: 'pm-unity-1',
    pageId: 'unity',
    pageName: 'Unity',
    pageSlug: '/unity',
    sectionId: 'unity-app-walkthrough',
    sectionName: 'Unity App Walkthrough',
    subModuleId: 'sub-unity-walkthrough',
    subModuleName: 'APP UI WALKTHROUGH',
    title: 'Unity App UI Walkthrough & Peer Discovery',
    description: 'Mobile app screen demonstration video for Android & iOS users.',
    mediaType: 'video',
    sourceType: 'localhost',
    mediaUrl: '/videos/unity-demo.mp4',
    isActive: true,
    createdAt: '2026-08-15',
  },

  // Community Life
  {
    id: 'pm-community-1',
    pageId: 'community-life',
    pageName: 'Community Life',
    pageSlug: '/events',
    sectionId: 'community-events-summits',
    sectionName: 'Events & Summits',
    subModuleId: 'sub-community-conclaves',
    subModuleName: 'NATIONAL CONCLAVES',
    title: 'Peers Global Conclaves & Summits Reel',
    description: 'Monthly meetings, national conclaves, retreats, and annual summits.',
    mediaType: 'video',
    sourceType: 'url',
    mediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    isActive: true,
    createdAt: '2026-08-18',
  },

  // About
  {
    id: 'pm-about-1',
    pageId: 'about',
    pageName: 'About',
    pageSlug: '/our-story',
    sectionId: 'about-our-story',
    sectionName: 'Our Story',
    subModuleId: 'sub-about-our-story-origin',
    subModuleName: 'THE BOTAD AWAKENING',
    title: 'Our Story — From Hospital Corridor to 1M Mission',
    description: 'From a hospital corridor to 1M mission: the origin story of Peers Global.',
    mediaType: 'video',
    sourceType: 'url',
    mediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    isActive: true,
    createdAt: '2026-08-10',
  },
  {
    id: 'pm-about-2',
    pageId: 'about',
    pageName: 'About',
    pageSlug: '/founder',
    sectionId: 'about-founder',
    sectionName: 'Dr. Pravin Parmar (Founder)',
    subModuleId: 'sub-about-founder-keynote',
    subModuleName: 'FOUNDER KEYNOTE',
    title: 'Dr. Pravin Parmar Founder Keynote Address',
    description: 'Founder keynote address, background, and vision of Dr. Pravin Parmar.',
    mediaType: 'video',
    sourceType: 'url',
    mediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    isActive: true,
    createdAt: '2026-08-12',
  },
]

export function getPageConfigBySlugOrId(identifier: string): WebsitePageConfig | undefined {
  if (!identifier) return WEBSITE_PAGES[0]
  const clean = identifier.toLowerCase().trim().replace(/^\//, '')

  // Direct matches by id, slug, or name
  const direct =
    WEBSITE_PAGES.find((p) => p.id.toLowerCase() === clean) ||
    WEBSITE_PAGES.find((p) => p.slug.toLowerCase().replace(/^\//, '') === clean) ||
    WEBSITE_PAGES.find((p) => (clean === '' || clean === 'home') && p.id === 'home') ||
    WEBSITE_PAGES.find((p) => p.name.toLowerCase() === clean)

  if (direct) return direct

  // Alias and subroute lookups
  if (
    clean === 'the-idea' ||
    clean === 'the-idea-our-world' ||
    clean === 'idea' ||
    clean === 'our-world' ||
    clean === '10-forms-of-collaboration' ||
    clean === 'the-territory' ||
    clean === 'the-citizens' ||
    clean === 'the-currency' ||
    clean === 'the-language' ||
    clean === 'culture-and-code' ||
    clean === '1-million-mission'
  ) {
    return WEBSITE_PAGES.find((p) => p.id === 'our-world')
  }

  if (clean === 'events' || clean === 'conclaves-events' || clean === 'conclaves' || clean === 'stories' || clean === 'community-life') {
    return WEBSITE_PAGES.find((p) => p.id === 'community-life')
  }

  if (clean === 'founder' || clean === 'dr-pravin-parmar' || clean === 'our-story' || clean === 'about' || clean === 'contact') {
    return WEBSITE_PAGES.find((p) => p.id === 'about')
  }

  if (clean === 'peer-circles' || clean === 'circle' || clean === 'circles') {
    return WEBSITE_PAGES.find((p) => p.id === 'circles')
  }

  if (clean === 'unity' || clean === 'unity-app') {
    return WEBSITE_PAGES.find((p) => p.id === 'unity')
  }

  if (clean === 'membership' || clean === 'apply' || clean === 'who-belongs-here') {
    return WEBSITE_PAGES.find((p) => p.id === 'membership')
  }

  if (clean === 'leadership') {
    return WEBSITE_PAGES.find((p) => p.id === 'leadership')
  }

  return undefined
}

export function getYouTubeEmbedUrl(url: string, autoplay = true): string | null {
  if (!url) return null
  const regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|&v=)([^#&?]*).*/
  const match = url.match(regExp)
  if (match && match[2].length === 11) {
    return `https://www.youtube.com/embed/${match[2]}${autoplay ? '?autoplay=1&mute=0&controls=1&rel=0' : ''}`
  }
  return null
}

export function extractYouTubeId(url: string): string | null {
  if (!url) return null
  const regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|&v=)([^#&?]*).*/
  const match = url.match(regExp)
  return match && match[2].length === 11 ? match[2] : null
}
